import { createElement } from 'lwc';
import For_Each_Example_NOob from 'c/for_Each_Example_NOob';

describe('c-for-each-example-n-oob', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-for-each-example-n-oob', {
            is: For_Each_Example_NOob
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});